apiVersion: v1
kind: Service
metadata:
  name: app1-nginx
  namespace: nginx
  labels:
    app: app1-nginx
  annotations:
    description: "Service to expose app1-nginx deployment"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: app1-nginx
  sessionAffinity: None
